# Generated by Django 5.1.3 on 2024-12-13 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='kurs nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='dars nomi')),
                ('lesson', models.TextField(blank=True, null=True, verbose_name="darsning ma'lumotlari")),
                ('curs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oquvmarkaz.curs', verbose_name='kurs nomi')),
            ],
        ),
    ]
